[common]
me = "Tarvus, Valtteri"

[[boards]]
organization = "waypoint-azure"
project = "HealthHub"
team = "HealthHub Team"

[[boards]]
organization = "if-it"
project = "Claims-Orchestrator"
team = "Claims-Orchestrator Team"

